title: Prairie Cantata
description: The Prairie Cantata is a meditation on the natural history, geography and geology of the Great Plains for chorus and nyckelharpe by composer Marya Hart.
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
