---
title: Prairie Cantata
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
contact: info@prairiecantata.info
description: The Prairie Cantata is a meditation on the natural history, geography
  and geology of the Great Plains for chorus and nyckelharpe by composer Marya Hart.
baseurl: ''
url: ''
markdown: kramdown
