backend:
  name: git-gateway
  branch: gh-pages # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}